server {
    listen 80;
    
    # Static files location
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API Proxy to Monolith (v1) & FastAPI (v2)
    # Allows the React app to hit /api and routes to the correct backend internally
    # depending on whether the strangler fig has cut over or not!
    location /api/v1/ {
        proxy_pass http://monolith:8000/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v2/ {
        proxy_pass http://orders-svc:8001/api/v2/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
